import type { DashboardSettings, Rule, StockPosition, TradeInput } from "@/lib/types";

export const SEED_ACCOUNT = {
  period_start: "2026-01-01",
  period_end: "2026-02-20",
  start_nav: 17752.48,
  end_nav: 7898.66,
  twr: -55.51,
  cash_start: 61.77,
  cash_end: -7852.2,
  cash_settled: -7503.2,
  stock_long: 13143.31,
  stock_short: 0,
  stock_total: 13143.31,
  options_long: 4781.77,
  options_short: -2166.67,
  options_total: 2615.1,
  interest_accrued: -7.55,
  interest_rate_est: 6.83,
  commissions_total: -84.17,
  margin_debt: 7852.2,
  mtm: -9762.1,
  trades_sales: 22529.2,
  trades_purchase: -30359,
};

export const SEED_SETTINGS: Omit<DashboardSettings, "id"> = {
  account_name: "Karen Markosyan",
  account_id: "U18542108",
  account_type: "Margin",
  interest_rate_est: 6.83,
  price_api: "yahoo",
  alpha_vantage_key: "",
};

export const SEED_STOCK_POSITIONS: Omit<StockPosition, "id" | "created_at">[] = [
  {
    ticker: "ADBE",
    shares: 50,
    cost_basis: 0,
    cost_price: 0,
    close_price: 258.61,
    unrealized_pl: -4569,
    notes: "RSU/ESPP grant. Zero cost basis. Was $349.99 at period start. No hedging. 74% of portfolio.",
  },
  {
    ticker: "IBKR",
    shares: 2.8605,
    cost_basis: 183.47,
    cost_price: 64.14,
    close_price: 74.395,
    unrealized_pl: 29.34,
    notes: "Vesting 2026-09-23. Small position. Up ~16%.",
  },
];

export const SEED_RULES: Omit<Rule, "id">[] = [
  {
    rule_number: 1,
    title: "The 2% Wall",
    description:
      "No single trade risks more than 2% of current NAV. No multi-lot trades until NAV > $20,000.",
    severity: "critical",
    enabled: true,
  },
  {
    rule_number: 2,
    title: "50% Stop — No Expiring Worthless",
    description:
      "If any position loses 50% of entry cost, close it. No exceptions.",
    severity: "critical",
    enabled: true,
  },
  {
    rule_number: 3,
    title: "Banned Strategies",
    description:
      "No naked long calls, no bearish spreads on earnings, no multi-lot entries, no same-day double entries, no averaging into losers.",
    severity: "critical",
    enabled: true,
  },
  {
    rule_number: 4,
    title: "Approved Strategies Only",
    description:
      "Bull call spreads, post-earnings iron condors, and very small defined-risk speculative trades.",
    severity: "high",
    enabled: true,
  },
  {
    rule_number: 5,
    title: "24-Hour Lockout",
    description:
      "After entering any trade: no modifications for 24 hours unless stop is hit.",
    severity: "high",
    enabled: true,
  },
  {
    rule_number: 6,
    title: "Weekly Risk Budget",
    description: "Max 5% of NAV at risk across all open positions.",
    severity: "high",
    enabled: true,
  },
  {
    rule_number: 7,
    title: "Direction Check",
    description: "If market regime conflicts with trade direction, require higher conviction and smaller size.",
    severity: "medium",
    enabled: true,
  },
  {
    rule_number: 8,
    title: "Pre-Trade Checklist",
    description: "Document risk, target, stop, catalyst, position count, and timing before every entry.",
    severity: "medium",
    enabled: true,
  },
  {
    rule_number: 9,
    title: "Win Protocol",
    description: "At +30% profit: trim. At +50%: close unless catalyst has not hit.",
    severity: "info",
    enabled: true,
  },
  {
    rule_number: 10,
    title: "Journal Mandate",
    description: "Every trade must have pre-trade and post-trade journal entries.",
    severity: "info",
    enabled: true,
  },
];

export const SEED_TRADES: TradeInput[] = [
  {
    ticker: "SPOT",
    strategy: "Bull Call Spread",
    legs: "430C / 460C",
    direction: "Bullish",
    entry_date: "2026-02-09",
    exit_date: "2026-02-10",
    expiry_date: "2026-02-20",
    status: "WIN",
    position_type: "option",
    cost_basis: 911,
    max_risk: 911,
    max_profit: 2089,
    realized_pl: 1613.92,
    unrealized_pl: null,
    return_pct: 177.2,
    commissions: 4.08,
    contracts: 1,
    catalyst: "Earnings",
    notes:
      "Bought 430C@15.50, sold 460C@6.39. Closed next day after massive earnings beat.",
    lesson: "✅ Best trade. Right sizing, timing, disciplined exit.",
    source: "manual",
    ib_symbols: ["SPOT 20FEB26 430 C", "SPOT 20FEB26 460 C"],
  },
  {
    ticker: "PINS",
    strategy: "Long Put",
    legs: "18.5P",
    direction: "Bearish",
    entry_date: "2026-02-11",
    exit_date: "2026-02-13",
    expiry_date: "2026-02-20",
    status: "WIN",
    position_type: "option",
    cost_basis: 105,
    max_risk: 105,
    max_profit: null,
    realized_pl: 292.9,
    unrealized_pl: null,
    return_pct: 278.9,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Earnings",
    notes: "Bought@1.05, sold@4.00. Post-earnings drop. 3.8x return.",
    lesson: "✅ Small size, high conviction, let it run",
    source: "manual",
    ib_symbols: ["PINS 20FEB26 18.5 P"],
  },
  {
    ticker: "PLTR",
    strategy: "Bull Call Spread",
    legs: "150C / 160C",
    direction: "Bullish",
    entry_date: "2026-02-02",
    exit_date: "2026-02-03",
    expiry_date: "2026-02-13",
    status: "WIN",
    position_type: "option",
    cost_basis: 363,
    max_risk: 363,
    max_profit: 637,
    realized_pl: 153.5,
    unrealized_pl: null,
    return_pct: 42.3,
    commissions: 3.5,
    contracts: 1,
    catalyst: "Earnings",
    notes: "Bought 150C@7.13, sold 160C@3.50. Quick flip. Cut winner slightly early.",
    lesson: "⚠️ Good execution but cut winner early (42% of max)",
    source: "manual",
    ib_symbols: ["PLTR 13FEB26 150 C", "PLTR 13FEB26 160 C"],
  },
  {
    ticker: "PANW",
    strategy: "Iron Condor",
    legs: "148P/152.5P/180C/185C",
    direction: "Neutral",
    entry_date: "2026-02-17",
    exit_date: "2026-02-20",
    expiry_date: "2026-02-20",
    status: "WIN",
    position_type: "option",
    cost_basis: 445,
    max_risk: 445,
    max_profit: 141,
    realized_pl: 108,
    unrealized_pl: null,
    return_pct: 24.3,
    commissions: 7,
    contracts: 1,
    catalyst: "Earnings",
    notes: "Credit $141. Closed for $26 debit. PANW stayed within wings.",
    lesson: "✅ Well-structured earnings IC. 78% credit captured.",
    source: "manual",
    ib_symbols: [
      "PANW 20FEB26 148 P",
      "PANW 20FEB26 152.5 P",
      "PANW 20FEB26 180 C",
      "PANW 20FEB26 185 C",
    ],
  },
  {
    ticker: "DDOG",
    strategy: "Iron Condor",
    legs: "95P/100P/125C/130C",
    direction: "Neutral",
    entry_date: "2026-02-09",
    exit_date: "2026-02-17",
    expiry_date: "2026-02-21",
    status: "WIN",
    position_type: "option",
    cost_basis: 445,
    max_risk: 445,
    max_profit: 248,
    realized_pl: 95,
    unrealized_pl: null,
    return_pct: 21.3,
    commissions: 7,
    contracts: 1,
    catalyst: "Post-Earnings",
    notes: "Opened for $248 credit. Closed for $146 debit. Held 8 days.",
    lesson: "✅ Managed properly — closed before expiry",
    source: "manual",
    ib_symbols: [
      "DDOG 21FEB26 95 P",
      "DDOG 21FEB26 100 P",
      "DDOG 21FEB26 125 C",
      "DDOG 21FEB26 130 C",
    ],
  },
  {
    ticker: "DKNG",
    strategy: "Long Put",
    legs: "24.5P",
    direction: "Bearish",
    entry_date: "2026-02-11",
    exit_date: "2026-02-12",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 79,
    max_risk: 79,
    max_profit: null,
    realized_pl: -20.82,
    unrealized_pl: null,
    return_pct: -26.4,
    commissions: 1.82,
    contracts: 1,
    catalyst: "Earnings",
    notes: "Bought@0.79, sold@0.60 next day. Quick cut.",
    lesson: "✅ Good loss management — small and fast",
    source: "manual",
    ib_symbols: ["DKNG 13FEB26 24.5 P"],
  },
  {
    ticker: "GRAB",
    strategy: "Long Put",
    legs: "4.5P (2x)",
    direction: "Bearish",
    entry_date: "2026-02-11",
    exit_date: "2026-02-12",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 70,
    max_risk: 70,
    max_profit: null,
    realized_pl: -28.8,
    unrealized_pl: null,
    return_pct: -41.1,
    commissions: 2.8,
    contracts: 2,
    catalyst: "Earnings",
    notes: "2x put@0.35, sold@0.22. Acceptable small loss.",
    lesson: "✅ Small sizing kept damage minimal",
    source: "manual",
    ib_symbols: ["GRAB 13FEB26 4.5 P"],
  },
  {
    ticker: "BABA",
    strategy: "Long Call",
    legs: "167.5C",
    direction: "Bullish",
    entry_date: "2026-02-13",
    exit_date: "2026-02-20",
    expiry_date: "2026-02-20",
    status: "LOSS",
    position_type: "option",
    cost_basis: 74,
    max_risk: 74,
    max_profit: null,
    realized_pl: -75.05,
    unrealized_pl: null,
    return_pct: -100,
    commissions: 1.05,
    contracts: 1,
    catalyst: "Speculation",
    notes: "167.5C@0.74. Expired worthless. BABA stayed below strike.",
    lesson: "❌ Expired to zero. Could have salvaged value.",
    source: "manual",
    ib_symbols: ["BABA 20FEB26 167.5 C"],
  },
  {
    ticker: "TMUS",
    strategy: "Long Put",
    legs: "185P",
    direction: "Bearish",
    entry_date: "2026-02-10",
    exit_date: "2026-02-13",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 163,
    max_risk: 163,
    max_profit: null,
    realized_pl: -164.05,
    unrealized_pl: null,
    return_pct: -100.6,
    commissions: 1.05,
    contracts: 1,
    catalyst: "Earnings",
    notes: "Bought@1.63. Expired worthless.",
    lesson: "❌ Held to zero — should have cut at 50% loss",
    source: "manual",
    ib_symbols: ["TMUS 13FEB26 185 P"],
  },
  {
    ticker: "WMT",
    strategy: "Long Call",
    legs: "140C",
    direction: "Bullish",
    entry_date: "2026-02-13",
    exit_date: "2026-02-20",
    expiry_date: "2026-02-20",
    status: "LOSS",
    position_type: "option",
    cost_basis: 172,
    max_risk: 172,
    max_profit: null,
    realized_pl: -172.7,
    unrealized_pl: null,
    return_pct: -100,
    commissions: 0.7,
    contracts: 1,
    catalyst: "Earnings",
    notes: "140C@1.72. Expired worthless. Strike too far OTM.",
    lesson: "❌ OTM + short DTE = expired worthless",
    source: "manual",
    ib_symbols: ["WMT 20FEB26 140 C"],
  },
  {
    ticker: "CSCO",
    strategy: "Long Call",
    legs: "88C",
    direction: "Bullish",
    entry_date: "2026-02-11",
    exit_date: "2026-02-13",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 178,
    max_risk: 178,
    max_profit: null,
    realized_pl: -178.77,
    unrealized_pl: null,
    return_pct: -100.4,
    commissions: 0.77,
    contracts: 1,
    catalyst: "Earnings",
    notes: "88C@1.78 with 2 DTE. Pure gamble. Expired.",
    lesson: "❌ 2 DTE = coin flip. Theta ate the premium",
    source: "manual",
    ib_symbols: ["CSCO 13FEB26 88 C"],
  },
  {
    ticker: "AMD",
    strategy: "Bear Call Spread",
    legs: "235C / 247.5C",
    direction: "Bearish",
    entry_date: "2026-01-30",
    exit_date: "2026-02-13",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 555,
    max_risk: 555,
    max_profit: 1245,
    realized_pl: -556.42,
    unrealized_pl: null,
    return_pct: -100.3,
    commissions: 1.42,
    contracts: 1,
    catalyst: "Earnings",
    notes: "235C@13.90, 247.5C@8.35. Max loss. Wrong direction.",
    lesson: "❌ Debit spread expired worthless",
    source: "manual",
    ib_symbols: ["AMD 13FEB26 235 C", "AMD 13FEB26 247.5 C"],
  },
  {
    ticker: "COIN",
    strategy: "Bear Put Spread",
    legs: "155P / 135P",
    direction: "Bearish",
    entry_date: "2026-02-11",
    exit_date: "2026-02-19",
    expiry_date: "2026-02-20",
    status: "LOSS",
    position_type: "option",
    cost_basis: 1187,
    max_risk: 1187,
    max_profit: 813,
    realized_pl: -712.69,
    unrealized_pl: null,
    return_pct: -60,
    commissions: 8.69,
    contracts: 2,
    catalyst: "Earnings",
    notes:
      "Long 155P, Short 135P. Opened across 2 days. Partial close then final close Feb 19.",
    lesson: "❌ Complex execution. Averaging into loser.",
    source: "manual",
    ib_symbols: ["COIN 20FEB26 155 P", "COIN 20FEB26 135 P"],
  },
  {
    ticker: "GOOGL",
    strategy: "Bull Put Spread",
    legs: "330P/320P (3x)",
    direction: "Bullish",
    entry_date: "2026-02-03",
    exit_date: "2026-02-06",
    expiry_date: "2026-02-07",
    status: "LOSS",
    position_type: "option",
    cost_basis: 2100,
    max_risk: 2100,
    max_profit: 900,
    realized_pl: -1334.72,
    unrealized_pl: null,
    return_pct: -63.6,
    commissions: 7.72,
    contracts: 3,
    catalyst: "Earnings",
    notes: "3x spread. GOOGL dropped post-earnings. 63.6% of max risk lost.",
    lesson: "❌ 3-lot = 11.8% of NAV. Oversized earnings bet.",
    source: "manual",
    ib_symbols: ["GOOGL 07FEB26 330 P", "GOOGL 07FEB26 320 P"],
  },
  {
    ticker: "AMZN",
    strategy: "Bear Put Spread",
    legs: "220P/210P (5x)",
    direction: "Bearish",
    entry_date: "2026-02-03",
    exit_date: "2026-02-09",
    expiry_date: "2026-02-13",
    status: "LOSS",
    position_type: "option",
    cost_basis: 3153,
    max_risk: 3153,
    max_profit: 1847,
    realized_pl: -3938.06,
    unrealized_pl: null,
    return_pct: -124.9,
    commissions: 26.06,
    contracts: 10,
    catalyst: "Earnings",
    notes:
      "5-lot opened TWICE in 3 min. Held 6 days through mounting loss. 22% of NAV destroyed.",
    lesson: "❌❌❌ Oversized. Impulsive double-entry. Broke every rule.",
    source: "manual",
    ib_symbols: ["AMZN 13FEB26 220 P", "AMZN 13FEB26 210 P"],
  },
  {
    ticker: "CEG",
    strategy: "Bull Call Spread",
    legs: "290C / 320C",
    direction: "Bullish",
    entry_date: "2026-02-19",
    expiry_date: "2026-04-17",
    status: "OPEN",
    position_type: "option",
    cost_basis: 1194.1,
    max_risk: 1194.1,
    max_profit: 1805.9,
    realized_pl: null,
    unrealized_pl: 72.5,
    return_pct: 6.07,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Nuclear/AI",
    notes: "56 DTE. Long expiry, minimal urgency. Near breakeven at ~$302.",
    lesson: "Manage with stop at $280 and profit-taking at 50-70% max.",
    breakeven: 301.94,
    stop_loss: 280,
    strike_long: 290,
    strike_short: 320,
    close_price_long: 27.016,
    close_price_short: 14.35,
    theta_per_day: -7,
    urgency: 1,
    peak_window: "Mar-Apr, hold patiently",
    hold_advice:
      "56 DTE. Long expiry, minimal urgency. Near breakeven at ~$302. Target 50-70% max profit ($900-$1,265). Nuclear/AI data center tailwinds.",
    exit_trigger: "Exit if CEG < $280. Take profits at 50-70% max.",
    best_case: "CEG rallies to $310-320+ -> $900-$1,806 profit.",
    exit_conservative: "Take profits at 50% max (~$900). Solid gain. Don't get greedy on a spread.",
    exit_balanced: "Hold to 70% max profit. Trail stop at 50%. Nuclear thesis has legs.",
    exit_aggressive: "Hold into April. Target max profit near $320+. AI data center demand is secular.",
    source: "manual",
    ib_symbols: ["CEG 17APR26 290 C", "CEG 17APR26 320 C"],
  },
  {
    ticker: "SNOW",
    strategy: "Bull Call Spread",
    legs: "180C / 200C",
    direction: "Bullish",
    entry_date: "2026-02-18",
    expiry_date: "2026-03-06",
    status: "OPEN",
    position_type: "option",
    cost_basis: 673.98,
    max_risk: 673.98,
    max_profit: 1326.02,
    realized_pl: null,
    unrealized_pl: -93.44,
    return_pct: -13.86,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Earnings",
    notes: "SNOW earnings Feb 25 AMC is the entire thesis. Binary setup.",
    lesson: "Close based on post-earnings gap behavior.",
    breakeven: 186.74,
    stop_loss: 170,
    strike_long: 180,
    strike_short: 200,
    close_price_long: 9.2733,
    close_price_short: 3.4679,
    theta_per_day: -25,
    urgency: 4,
    peak_window: "Feb 25-26 (post-earnings)",
    hold_advice:
      "SNOW earnings Feb 25 AMC is the ENTIRE thesis. IV is elevated. This is binary - SNOW gaps or you lose. 14 DTE but only the earnings date matters.",
    exit_trigger: "Feb 26 AM: SNOW > $187 -> hold. SNOW flat/down -> close immediately.",
    best_case: "SNOW beats -> gap to $195-210 -> spread worth $600-$1,326.",
    exit_conservative: "Sell Feb 24 for IV premium (~$350-450). Avoid the coin flip.",
    exit_balanced: "Hold through earnings. Close Feb 26 based on gap.",
    exit_aggressive: "Hold through earnings and ride to Mar 6 if momentum confirms.",
    source: "manual",
    ib_symbols: ["SNOW 06MAR26 180 C", "SNOW 06MAR26 200 C"],
  },
  {
    ticker: "NVDA",
    strategy: "Bull Call Spread",
    legs: "200C / 210C",
    direction: "Bullish",
    entry_date: "2026-02-13",
    expiry_date: "2026-02-27",
    status: "OPEN",
    position_type: "option",
    cost_basis: 129.42,
    max_risk: 129.42,
    max_profit: 870.58,
    realized_pl: null,
    unrealized_pl: 20.58,
    return_pct: 15.9,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Earnings",
    notes: "7 DTE earnings lottery with asymmetric payoff.",
    lesson: "Close immediately if post-earnings reaction is weak.",
    breakeven: 201.29,
    stop_loss: 185,
    strike_long: 200,
    strike_short: 210,
    close_price_long: 1.995,
    close_price_short: 0.495,
    theta_per_day: -18,
    urgency: 5,
    peak_window: "Feb 25-26 (post-earnings)",
    hold_advice:
      "NVDA earnings Feb 25 AMC. 7 DTE. Needs ~6% gap to breakeven. Pure lottery - $129 for $871 max (6.7:1).",
    exit_trigger: "Feb 26 AM: NVDA > $195 -> hold. NVDA flat/down -> close immediately.",
    best_case: "NVDA beats -> gap to $210-220 -> spread worth $500-$871.",
    exit_conservative: "Sell Feb 24 for IV expansion (~$40-70). Recover 30-55% of cost.",
    exit_balanced: "Hold through earnings. Close Feb 26.",
    exit_aggressive: "Hold through earnings and expiry for 6.7:1 outcome.",
    source: "manual",
    ib_symbols: ["NVDA 27FEB26 200 C", "NVDA 27FEB26 210 C"],
  },
  {
    ticker: "DELL",
    strategy: "Bull Call Spread",
    legs: "122C / 130C",
    direction: "Bullish",
    entry_date: "2026-02-20",
    expiry_date: "2026-02-27",
    status: "OPEN",
    position_type: "option",
    cost_basis: 324.4,
    max_risk: 324.4,
    max_profit: 475.6,
    realized_pl: null,
    unrealized_pl: 23.62,
    return_pct: 7.28,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Earnings",
    notes: "DELL earnings Feb 26 AMC. Expiry the next day.",
    lesson: "Treat as event-driven binary with strict morning-after exit.",
    breakeven: 125.24,
    stop_loss: 115,
    strike_long: 122,
    strike_short: 130,
    close_price_long: 6.7922,
    close_price_short: 3.312,
    theta_per_day: -20,
    urgency: 5,
    peak_window: "Feb 27 (post-earnings, expiry day)",
    hold_advice:
      "DELL earnings Feb 26 AMC. Expiry Feb 27. Needs 5.2% rally to breakeven. AI server backlog supports upside thesis.",
    exit_trigger: "Feb 27 AM: DELL > $125 -> hold. DELL flat/down -> close immediately.",
    best_case: "DELL beats on AI -> gap to $128-135+ -> spread worth $300-$476.",
    exit_conservative: "Sell Feb 25 for IV expansion (~$100-150).",
    exit_balanced: "Hold through earnings. Close Feb 27 AM.",
    exit_aggressive: "Hold through earnings and expiry for full payout window.",
    source: "manual",
    ib_symbols: ["DELL 27FEB26 122 C", "DELL 27FEB26 130 C"],
  },
  {
    ticker: "HOOD",
    strategy: "Long Call (ex-diagonal)",
    legs: "85C Mar27",
    direction: "Bullish",
    entry_date: "2026-02-10",
    expiry_date: "2026-03-27",
    status: "OPEN",
    position_type: "option",
    cost_basis: 680.4,
    max_risk: 680.4,
    max_profit: null,
    realized_pl: null,
    unrealized_pl: -410.46,
    return_pct: -60.33,
    commissions: 2.1,
    contracts: 1,
    catalyst: "Crypto",
    notes: "Short 95C expired; now naked long 85C Mar with time decay pressure.",
    lesson: "Either convert back to spread or cut remaining value.",
    breakeven: 91.8,
    stop_loss: 70,
    strike_long: 85,
    strike_short: null,
    close_price_long: 2.7412,
    close_price_short: 0.0418,
    theta_per_day: -12,
    urgency: 3,
    peak_window: "If crypto rallies: any time",
    hold_advice:
      "Short 95C Feb expired -> naked long 85C Mar. HOOD at ~$76 needs 21% rally. 35 DTE, bleeding ~$12/day.",
    exit_trigger: "If call < $1.00: close. If HOOD > $83: sell short call to recreate spread.",
    best_case: "Crypto rebound -> HOOD $90+ -> call worth $500-1500+.",
    exit_conservative: "Sell now and recover remaining time value (~$100-250).",
    exit_balanced: "Sell Mar 95C against it to create spread and reduce bleed.",
    exit_aggressive: "Hold through March for crypto cycle rebound, accepting low probability.",
    source: "manual",
    ib_symbols: ["HOOD 27MAR26 85 C"],
  },
];

export const TRADE_AUTOPSY_REFERENCE = [
  {
    ticker: "SPOT",
    strategy: "BCS 430/460C",
    days: 1,
    pl: 1613.92,
    risk: 911,
    ret: 177,
    status: "WIN",
    detail:
      "Bought 430C@15.50, sold 460C@6.39. Next morning after massive earnings beat: closed at 56.76 / 31.47. Captured 54% of max profit in 24 hours.",
    good: "Right sizing (5.1% NAV), disciplined exit at 54% max, 1-day hold, didn't get greedy.",
    lesson: "✅ The textbook trade. Repeat this pattern.",
  },
  {
    ticker: "PINS",
    strategy: "Long Put 18.5P",
    days: 2,
    pl: 292.9,
    risk: 105,
    ret: 279,
    status: "WIN",
    detail: "Bought@1.05, sold@4.00. PINS dropped post-earnings. 3.8x return on $105 risk.",
    good: "0.6% of NAV true lottery sizing. Let it run and took profits at 3.8x.",
    lesson: "✅ When spec bets are this small, math works: one PINS pays for ten DKNGs.",
  },
  {
    ticker: "PLTR",
    strategy: "BCS 150/160C",
    days: 1,
    pl: 153.5,
    risk: 363,
    ret: 42,
    status: "WIN",
    detail: "Bought@3.63 debit. Next day sold at 5.20 (7.70 - 2.50). 42% of $636 max.",
    good: "Fast in, fast out. Banked 42% overnight.",
    lesson: "⚠️ Perfect execution. Could have held for more, but taking profit never killed anyone.",
  },
  {
    ticker: "PANW",
    strategy: "IC 148P/152.5P/180C/185C",
    days: 3,
    pl: 108,
    risk: 445,
    ret: 24,
    status: "WIN",
    detail: "Collected $141 credit. Closed at $26 debit. PANW stayed in wings. 78% credit captured.",
    good: "Premium selling done right. Closed at 78% instead of waiting for max.",
    lesson: "✅ This is your edge. Iron condors post-earnings = 2-0.",
  },
  {
    ticker: "DDOG",
    strategy: "IC 95P/100P/125C/130C",
    days: 8,
    pl: 95,
    risk: 445,
    ret: 21,
    status: "WIN",
    detail: "Credit $248, closed at $153 debit. 38% captured in 8 days.",
    good: "Right strategy, won.",
    lesson: "⚠️ IC management: close faster. 50% credit in 3 days > 38% in 8 days.",
  },
  {
    ticker: "DKNG",
    strategy: "Long Put 24.5P",
    days: 1,
    pl: -20.82,
    risk: 79,
    ret: -26,
    status: "LOSS",
    detail: "Bought@0.79, sold@0.60 next day. Quick recognition, fast exit.",
    good: "Cut fast. Lost 26% not 100%.",
    lesson: "✅ Actually good loss management. Small and fast.",
  },
  {
    ticker: "GRAB",
    strategy: "Long Put 4.5P (2x)",
    days: 1,
    pl: -28.8,
    risk: 70,
    ret: -41,
    status: "LOSS",
    detail: "2x put@0.35, sold@0.22 next day. Small sizing, quick exit.",
    good: "Cut fast, small position, acceptable loss.",
    lesson: "✅ The 2-lot was fine here because total risk was only $70.",
  },
  {
    ticker: "BABA",
    strategy: "Long Call 167.5C",
    days: 7,
    pl: -75.05,
    risk: 74,
    ret: -100,
    status: "LOSS",
    detail: "167.5C@0.74. Held 7 days. Expired worthless.",
    good: "Small sizing at $74.",
    lesson: "❌ Had residual value mid-week. Could have recovered $20-30. Never hold to zero.",
  },
  {
    ticker: "TMUS",
    strategy: "Long Put 185P",
    days: 3,
    pl: -164.05,
    risk: 163,
    ret: -100,
    status: "LOSS",
    detail: "Bought@1.63. TMUS stayed above 185. Expired worthless Feb 13.",
    good: "Nothing.",
    lesson: "❌ Should have cut at 50% loss ($82). Instead lost full $164.",
  },
  {
    ticker: "WMT",
    strategy: "Long Call 140C",
    days: 7,
    pl: -172.7,
    risk: 172,
    ret: -100,
    status: "LOSS",
    detail: "140C@1.72. WMT was ~$105 at entry. Needed a 33% move in 7 days.",
    good: "Nothing.",
    lesson: "❌ Strike 33% OTM = near zero probability.",
  },
  {
    ticker: "CSCO",
    strategy: "Long Call 88C",
    days: 2,
    pl: -178.77,
    risk: 178,
    ret: -100,
    status: "LOSS",
    detail: "88C@1.78 with 2 DTE. Expired worthless.",
    good: "Nothing.",
    lesson: "❌ 2 DTE naked long call = theta burn.",
  },
  {
    ticker: "AMD",
    strategy: "Bear Call Spread 235/247.5C",
    days: 14,
    pl: -556.42,
    risk: 555,
    ret: -100,
    status: "LOSS",
    detail: "Debit bear call spread. Held 14 days to expiry. Wrong direction on AMD.",
    good: "At least it was 1-lot.",
    lesson: "❌ Bearish AMD was wrong read. No exit plan.",
  },
  {
    ticker: "COIN",
    strategy: "Bear Put 155P/135P",
    days: 8,
    pl: -712.69,
    risk: 1187,
    ret: -60,
    status: "LOSS",
    detail:
      "Opened Feb 11. Added Feb 12 at worse price. Partial close same day. Final close Feb 19.",
    good: "Nothing.",
    lesson:
      "❌ Averaging into a loser and restructuring mid-trade is how $700 losses happen.",
  },
  {
    ticker: "GOOGL",
    strategy: "Bull Put 330P/320P (3x)",
    days: 3,
    pl: -1334.72,
    risk: 2100,
    ret: -64,
    status: "LOSS",
    detail: "3-lot = 11.8% NAV on one earnings play. Exit split across 2 days.",
    good: "Nothing.",
    lesson: "❌ Sizing killed the trade.",
  },
  {
    ticker: "AMZN",
    strategy: "Bear Put 220P/210P (5x)",
    days: 6,
    pl: -3938.06,
    risk: 3153,
    ret: -125,
    status: "LOSS",
    detail:
      "14:15:56 opened 5 contracts. 14:18:59 opened 5 more. Held 6 days and exited in pieces.",
    good: "Absolutely nothing.",
    lesson:
      "❌❌❌ Impulsive double-entry and no stop loss destroyed 22% of NAV on one position.",
  },
] as const;
